### ISSUE TITLE
Build failed, badges are broken

### ISSUE THREAD

**Issue by beefon** [AndreyZarembo/EasyDi#16]

**Comment by beefon** [comment]
Also, there are 3 duplicated badges apparently (cocoapods)

**Comment by dimorinny** [comment]
+1

**Comment by AndreyZarembo** [comment]
<img width="682" alt="2018-04-13 11 41 25" src="https://user-images.githubusercontent.com/473710/38725310-a41858e4-3f0f-11e8-9d2d-1481284d9307.png">
ok?

**Comment by beefon** [comment]
No yet unfortunately.
<img width="600" alt="2018-04-13 11 47 03" src="https://user-images.githubusercontent.com/640610/38725574-72595e10-3f10-11e8-897a-a466e34e6ef5.png">

**Comment by AndreyZarembo** [comment]
Badge is static and going from 'https://img.shields.io/cocoapods'
There's the link to img, you can try to open: https://img.shields.io/cocoapods/v/EasyDi.svg?style=flat
So there's no problems with this pod )
