### ISSUE TITLE
Поддержка многопоточности

### ISSUE THREAD

**Issue by SergeyKrupov** [AndreyZarembo/EasyDi#20]
Привет,
текущая реализация DIContext-a судя по всему, не предназначена для использования одновременно из нескольких потоков без дополнительной синхронизации "снаружи". Т.е. создавать объекты из разных потоков используя Assembly получается небезопасно.

Есть возможность доработать существующий класс контекста для включения "потокобезопасности" либо выделение нового класса потокобезопасного контекста?

**Comment by SergeyKrupov** [comment]
[Предлагаемый фикс](https://github.com/SergeyKrupov/EasyDi/commit/8fb96ca1df14c075c8867555ff46c08f6be876d4)

**Comment by AndreyZarembo** [comment]
Сергей, привет! Потокобезопасность, это то, чего действительно не хватает. Здорово, что ты предложил фикс, выглядит похожим на правду. Но чтобы проверить действительно ли это решает проблему безопасности потоков нужны тесты, который старый код не пройдет, а код с твоими изменениями - сможет. И Pull Request, чтобы я мог залить это в ветку develop. Сделаешь?

**Comment by SergeyKrupov** [comment]
Сделано

**Comment by dvi** [comment]
version 1.5.0
